version: '3.8'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: youtube_caption_summary
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  backend:
    build: ./backend
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql://user:password@db:5432/youtube_caption_summary
      SECRET_KEY: your-secret-key
    depends_on:
      - db
    volumes:
      - ./backend:/app

volumes:
  db_data:
